# Generated by Django 3.0.7 on 2020-07-20 21:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('file', models.FileField(upload_to='files')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('house', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=6)),
                ('name_on_card', models.CharField(max_length=100)),
                ('card_num', models.CharField(max_length=16)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
